### ISSUE TITLE
improve local BE development experience

### ISSUE THREAD

**Issue by halo123u** [JDGiardino/BGG-Companion#35]
restart server automatically on changes
add alias for starting backend 
add alias for running tests

**Comment by nickdibari** [comment]
For point 1 if you all run Flask in development mode it should auto-reload the app server whenever changes are made to any of the project python scripts. By default development mode is not enabled (because one of the things that development mode gives you is a real-time debugger on unhandled exception which would be catastrophic in production) but there's an environment variable called `FLASK_ENV` that you can set to `development` to enabled development mode.

For the aliases you all could set up a Makefile or something similar to make it easier to run your commands. That could play nicely with the first point as you can have a Makefile command for running in development mode, like

```cmake
run-debug: FLASK_ENV=development poetry run flask run
```

**Comment by JDGiardino** [comment]
@nickdibari  Yeah!!! I had recalled there being a mode where you don't need to restart the app and changes being there and meant to look into this.  

For the aliases what I was thinking originally was within the .toml file having a section like [tool.poetry.aliases] and storing aliases in there so `poetry run <alias>` I think would just work?  Makefile is something else could look into.

**Comment by JDGiardino** [comment]
Referencing this documentation https://makefiletutorial.com/
